name: isweep-simulate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21
  - pandas
  - scipy>=1.7
  - matplotlib
  - seaborn
  - networkx
  - tskit
  - pyslim
  - tszip
  - msprime
  - snakemake
  - pip
  # - pip:
  #     - isweep
