# isweep real data analysis part 1 (scan)
# Seth D. Temple, sdtemple@uw.edu
# April 26, 2023

# setup macro folder
macro=str(config['CHANGE']['FOLDERS']['STUDY'])
low=int(str(config['CHANGE']['ISWEEP']['CHRLOW']))
high=int(str(config['CHANGE']['ISWEEP']['CHRHIGH']))

# copy and paste maps
import os
folder_name = macro
if not os.path.exists(folder_name):
    os.makedirs(folder_name)
folder_name = macro + '/maps'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)
mapfol=str(config['CHANGE']['EXISTING']['MAPS'])
mappre=str(config['CHANGE']['EXISTING']['MAPPRE'])
mapsuf=str(config['CHANGE']['EXISTING']['MAPSUF'])
import shutil
source_file = "path/to/source/file"
destination_file = "path/to/destination/file"
for i in range(low,high+1):
    source_file = mapfol+'/'+mappre+str(i)+mapsuf
    destination_file = macro+'/maps/chr'+str(i)+'.map'
    shutil.copy(source_file, destination_file)

# include .smk files with rules
include: 'rules/scan.smk'
include: 'rules/interesting.smk'
include: 'rules/samples.smk'

# snakemake all -c1 -n
rule all:
    input:
        macro+'/excess.ibd.tsv',
        macro+'/excess.region.ibd.tsv',
        macro+'/roi.tsv',
        macro+'/excludesamples.txt',
        macro+'/ibdne.ne',
    output:
        yaml=macro+'/arguments.scan.yaml',
    shell:
        'cp {config[CHANGE][FOLDERS][YAML]} {output.yaml}'
