name: isweep-roi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - snakemake
  - numpy>=1.21
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - jupyter
  - notebook
